#words generated by Bacon Ipsum (https://baconipsum.com);
print('Bacon ipsum dolor amet pastrami picanha pork meatloaf biltong turducken shankle shoulder kielbasa cow fatback ground round ham tri-tip.')
print('Brisket short loin ham short ribs hamburger beef.')
print('Biltong bresaola brisket pork, shoulder salami short ribs pastrami tail jowl.');
print('\"Boudin hamburger venison cupim.\"')